apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictive-maintenance-api
  labels:
    app: predictive-maintenance-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predictive-maintenance-api
  template:
    metadata:
      labels:
        app: predictive-maintenance-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
        - name: api
          image: adityagupta20/predictive-maintenance-api:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: SERVICE_NAME
              value: "predictive-maintenance-api"
            - name: LOG_LEVEL
              value: "INFO"
            - name: MODEL_VERSION
              value: "prod"
            - name: MODEL_PATH
              value: "models/best_model.joblib"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
